version: '3.9'

services:
  app:
    build:
      context: .
    container_name: portfolio_pages
    tty: true
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default

