import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full bg-gray-800 text-white p-4">
          <div className="max-w-5xl mx-auto">
            <a href="/" className="text-lg font-bold hover:underline">
              Home
            </a>
          </div>
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-4 gap-8">
          {children}
        </main>
      </body>
    </html>
  );
}
